package com.ssm.mapper;

import com.ssm.pojo.Artist;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
@Component("artistMapper")
public interface ArtistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artist
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artist
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    int insert(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artist
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    int insertSelective(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artist
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    Artist selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artist
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    int updateByPrimaryKeySelective(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artist
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artist
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    int updateByPrimaryKey(Artist record);

    List<Artist> selectAllArtist(Map<String,Object> map);
    int selectCountAllArtist(Map<String,Object> map);

    Artist selectReArtist(Map<String,Object> map);
    int insertArtist(Artist artist);

    //后台 删除艺人
    int deleteArtistById(String[] id);

    //后台 修改艺人
    Artist selectArtistById(int lid);
    int updateArtist(Artist artist);
    int selectReInArtist(Map<String,Object> map);

    int selectaidByName(String name);
}