package com.ssm.mapper;

import com.ssm.pojo.Commend;
import com.ssm.pojo.Commend;

import java.util.List;
import java.util.Map;

public interface CommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    int insert(Commend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    int insertSelective(Commend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    Commend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    int updateByPrimaryKeySelective(Commend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commend
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    int updateByPrimaryKey(Commend record);

    //后台 列出所有符合条件的
    List<Commend> selectAllCommend(Map<String,Object> map);
    //总条数
    int selectCountAllCommend(Map<String,Object> map);

    //增加
    //查重
    Commend selectReCommend(Map<String, Object> map);
    Commend selectAlidByName(Map<String, Object> map);
    int insertCommend(Commend commend);

    //删除
    int deleteCommendById(String[] id);

    //修改
    Commend selectCommendById(int id);
    int updateCommend(Commend Commend);
    int selectIdByName(Commend commend);
}