package com.ssm.mapper;

import com.ssm.pojo.Label;
import com.ssm.pojo.User;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component("labelMapper")
public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    int insertSelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    Label selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    int updateByPrimaryKeySelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    int updateByPrimaryKey(Label record);


    //后台 列出所有符合条件的
    List<Label> selectAllLabel(Map<String,Object> map);
    //总条数
    int selectCountAllLabel(Map<String,Object> map);

    //后台 创建标签
    //先查询是否有重复
    Label selectReLabel(Map<String,Object> map);
    //向数据库添加标签
    int insertLabel(Label label);

    //后台 删除标签
    int deleteLabelById(String[] id);

    //后台 修改标签
    Label selectLabelById(int lid);
    int updateLabel(Label label);
    int selectReInLabel(Map<String,Object> map);

}