package com.ssm.mapper;

import com.ssm.pojo.Music;

import java.util.List;
import java.util.Map;

public interface MusicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    int insert(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    int insertSelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    Music selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    int updateByPrimaryKeySelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    int updateByPrimaryKey(Music record);


    List<Music> selectAllMusic(Map<String,Object> map);
    int selectCountAllMusic(Map<String,Object> map);

    Music selectReMusic(Map<String, Object> map);
    Music selectAlid(Map<String, Object> map);
    int insertMusic(Music music);

    int deleteMusicById(String[] id);

    Music selectMusicById(int mid);
    int selectReInMusic(Map<String,Object> map);
    int updateMusic(Music music);

    List<Music> selectAlbumMusic(int alid);
    int selectCountAlbumMusic(int alid);

    int selectAlidByMid(int mid);
    int selectMidByName(Music music);
}