package com.ssm.pojo;

public class Album {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.alid
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    private Integer alid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.title
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.created
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    private String created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.aid
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    private String aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.rc
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    private String rc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.label
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.text
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    private String text;
    private String artists;
    private Integer lid;

    public Album() {
    }

    public Album(String title, String created, String aid, String rc, String label, String text, String artists, Integer lid) {
        this.title = title;
        this.created = created;
        this.aid = aid;
        this.rc = rc;
        this.label = label;
        this.text = text;
        this.artists = artists;
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.alid
     *
     * @return the value of album.alid
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public Integer getAlid() {
        return alid;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.alid
     *
     * @param alid the value for album.alid
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public void setAlid(Integer alid) {
        this.alid = alid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.title
     *
     * @return the value of album.title
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.title
     *
     * @param title the value for album.title
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.created
     *
     * @return the value of album.created
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.created
     *
     * @param created the value for album.created
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.aid
     *
     * @return the value of album.aid
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.aid
     *
     * @param aid the value for album.aid
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public void setAid(String aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.rc
     *
     * @return the value of album.rc
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public String getRc() {
        return rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.rc
     *
     * @param rc the value for album.rc
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public void setRc(String rc) {
        this.rc = rc == null ? null : rc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.label
     *
     * @return the value of album.label
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.label
     *
     * @param label the value for album.label
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.text
     *
     * @return the value of album.text
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public String getText() {
        return text;
    }


    public String getArtists() {
        return artists;
    }

    public void setArtists(String artists) {
        this.artists = artists;
    }

    public Integer getLid() {
        return lid;
    }

    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.text
     *
     * @param text the value for album.text
     *
     * @mbggenerated Mon Mar 13 13:37:35 CST 2023
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}