package com.ssm.pojo;

public class Artist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artist.aid
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artist.name
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artist.dob
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    private String dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artist.about
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    private String about;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artist.aid
     *
     * @return the value of artist.aid
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artist.aid
     *
     * @param aid the value for artist.aid
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artist.name
     *
     * @return the value of artist.name
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artist.name
     *
     * @param name the value for artist.name
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artist.dob
     *
     * @return the value of artist.dob
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public String getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artist.dob
     *
     * @param dob the value for artist.dob
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public void setDob(String dob) {
        this.dob = dob == null ? null : dob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artist.about
     *
     * @return the value of artist.about
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public String getAbout() {
        return about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artist.about
     *
     * @param about the value for artist.about
     *
     * @mbggenerated Sun Mar 12 17:02:14 CST 2023
     */
    public void setAbout(String about) {
        this.about = about == null ? null : about.trim();
    }
}