package com.ssm.pojo;

public class Commend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.id
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.name
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.title
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.subtitle
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commend.alid
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    private Integer alid;
    private  String album;

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.id
     *
     * @return the value of commend.id
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.id
     *
     * @param id the value for commend.id
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.name
     *
     * @return the value of commend.name
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.name
     *
     * @param name the value for commend.name
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.title
     *
     * @return the value of commend.title
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.title
     *
     * @param title the value for commend.title
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.subtitle
     *
     * @return the value of commend.subtitle
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.subtitle
     *
     * @param subtitle the value for commend.subtitle
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commend.alid
     *
     * @return the value of commend.alid
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public Integer getAlid() {
        return alid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commend.alid
     *
     * @param alid the value for commend.alid
     *
     * @mbggenerated Thu Mar 16 11:22:16 CST 2023
     */
    public void setAlid(Integer alid) {
        this.alid = alid;
    }
}