package com.ssm.pojo;

public class Label {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.lid
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    private Integer lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.name
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.lid
     *
     * @return the value of label.lid
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.lid
     *
     * @param lid the value for label.lid
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.name
     *
     * @return the value of label.name
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.name
     *
     * @param name the value for label.name
     *
     * @mbggenerated Sun Mar 12 11:11:13 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}