package com.ssm.pojo;

public class Music {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.mid
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.alid
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    private Integer alid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.min
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    private String min;
    private String title;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.mid
     *
     * @return the value of test.mid
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */


    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.mid
     *
     * @param mid the value for test.mid
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.alid
     *
     * @return the value of test.alid
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    public Integer getAlid() {
        return alid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.alid
     *
     * @param alid the value for test.alid
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    public void setAlid(Integer alid) {
        this.alid = alid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.min
     *
     * @return the value of test.min
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    public String getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.min
     *
     * @param min the value for test.min
     *
     * @mbggenerated Wed Mar 15 09:09:39 CST 2023
     */
    public void setMin(String min) {
        this.min = min == null ? null : min.trim();
    }
}