package com.ssm.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mail
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.screenName
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    private String screenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.group
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    private String group;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mail
     *
     * @return the value of users.mail
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mail
     *
     * @param mail the value for users.mail
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.screenName
     *
     * @return the value of users.screenName
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public String getScreenname() {
        return screenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.screenName
     *
     * @param screenname the value for users.screenName
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public void setScreenname(String screenname) {
        this.screenname = screenname == null ? null : screenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.group
     *
     * @return the value of users.group
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.group
     *
     * @param group the value for users.group
     *
     * @mbggenerated Thu Mar 09 12:46:27 CST 2023
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }
}